# Generated by Django 2.1 on 2018-08-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField()),
                ('lesson_category', models.IntegerField()),
                ('lesson_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Person'),
        ),
    ]
