# Generated by Django 2.1 on 2018-08-26 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=128, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性別'),
        ),
    ]
