# Generated by Django 2.1 on 2018-08-29 04:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20180829_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='joined_at',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(datetime.date(2018, 8, 29))], verbose_name='受講日'),
        ),
    ]
